<?php
define('DB_HOST',"localhost");
define('DB_USER',"meli");
define('DB_PWD',"melieric2001");
define('DB_NAME',"orientech");
define('DB_TABLE_CDES',"cdes");
define('DB_TABLE_FILIERE',"filiere");
define('DB_TABLE_TEMOIGNAGE',"temoignage");
define('DB_TABLE_ELEVE',"eleve");
define('DB_TABLE_FORUME',"forum");
define('DB_TABLE_FORUME_REPONSE',"reponse_forum");
define('DB_TABLE_USERS',"users");
define('URL_BD',"/wamp64/www/php/OrienTech/back_end/bd/");
define('URL_TMP',"/wamp64/www/php/OrienTech/back_end/template/");
define('URL_CONTROLLER',"/wamp64/www/php/OrienTech/back_end/controller/");
define('URL_CONTROLLER2',"/php/OrienTech/back_end/controller/");
define('URL_FONCTION',"/wamp64/www/php/OrienTech/back_end/fonction/");
define('URL_MODEL',"/wamp64/www/php/OrienTech/back_end/model/");
define('URL_VAR',"/wamp64/www/php/OrienTech/back_end/var/");
define('URL_CSS',"/wamp64/www/php/OrienTech/front-end/assets/css/");
define('URL_CSS2',"/php/OrienTech/front-end/assets/css/");
define('URL_IMG',"/php/OrienTech/front-end/assets/img/");
define('URL_IMAGES',"/php/OrienTech/front-end/assets/images/");
define('URL_JS',"/wamp64/www/php/OrienTech/front-end/assets/js/");
define('URL_JS2',"/php/OrienTech/front-end/assets/js/");
define('URL_PAGE',"/wamp64/www/php/OrienTech/front-end/");
define('DB_TABLE_COMMENTAIRES',"commentaires");
define('URL',"http://".DB_HOST."/my_projetcs\/".DB_NAME."/front-end");
?>